# The URL the site will be built for
base_url = "https://propixelizer.github.io/docs"
title = "ProPixelizer"
description = "Documentation for the ProPixelizer package for Unity"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola_easydocs_theme"

author = "Elliot Bentine"
generate_sitemap = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
bottom_footnotes = false

[extra]
# Put all your custom variables here
easydocs_heading_threshold = 1
logo = "head.png"
favicon = "propixelizer.ico"
package_version = "2.0.1"